show databases;

create database customer;
show databases;
use customer;

-- Q1. Analyze the total revenue generated by male and female customers
select gender, 
	   sum(purchase_amount) as revenue
from customer
group by gender;


-- Q2. Identify customers who used discounts but spent more than the average purchase amount.
SELECT customer_id,
       purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount >= (
        SELECT AVG(purchase_amount)
        FROM customer
      );

SELECT AVG(purchase_amount)
FROM customer;


-- Q3. Determine the top 5 products with the highest average review ratings.
SELECT item_purchased,
       ROUND(AVG(review_rating),2) AS average_product_rating
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;


-- Q4. Compare the average purchase amount between Standard and Express shipping methods.

SELECT shipping_type,
       AVG(purchase_amount) AS average_purchase
FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;


-- Q5. Compare average spending and total revenue between subscribed and non-subscribed customers.

SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,
         avg_spend;

-- Q6. Identify the top 5 products with the highest percentage of discounted purchases.

SELECT item_purchased,
       ROUND(
           SUM(
               CASE
                   WHEN discount_applied = 'Yes'
                   THEN 1
                   ELSE 0
               END
           ) * 100.00 / COUNT(*),2
       ) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

SELECT VERSION();

-- Q7. Segment customers into New, Returning, and Loyal categories based on previous purchases.

WITH customer_type AS (
    SELECT customer_id,
           previous_purchases,
           CASE
               WHEN previous_purchases = 1
                    THEN 'New'
               WHEN previous_purchases BETWEEN 2 AND 10
                    THEN 'Returning'
               ELSE 'Loyal'
           END AS customer_segment
    FROM customer
)

SELECT customer_segment,
       COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;


-- Q8. Find the top 3 most purchased products within each product category.

WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (
               PARTITION BY category
               ORDER BY COUNT(customer_id) DESC
           ) AS item_rank
    FROM customer
    GROUP BY category,
             item_purchased
)

SELECT item_rank,
       category,
       item_purchased,
       total_orders
FROM item_counts
WHERE item_rank <= 3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases)also likely to subscribe?

SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. Revenue contribution of each age group.

SELECT age_group,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;

-- 11. Find the total number of customers.
select count(*) as 'Total Customers'
from customer;

-- 12. Find the average purchase amount.
select avg(purchase_amount) as 'Average Purchase Amount'
from customer;

-- 13. Find the highest and lowest purchase amounts
select max(purchase_amount) as 'Highest purchase',
	   min(purchase_amount) as 'Lowest Purchase'
from customer;

-- 14. Count customers in each age group.
select age_group,
count(*) as 'Total Customers'
from customer
group by age_group;

-- 15. Which payment method is used the most?
select payment_method,
count(*) as 'TotalCustomers'
from customer
group by payment_method
order by TotalCustomers desc;

-- 16. Find the most purchased product.
select item_purchased,
count(*) as TotalOrders
from customer
group by item_purchased
order by TotalOrders desc
limit 1;

-- 17. Which season generates the highest revenue?
select season,
count(*) as TotalOrders
from customer
group by season
order by TotalOrders desc;

-- 18. Which category generates the highest revenue?
select category,
count(*) as TotalOrders
from customer
group by category
order by TotalOrders desc;

-- 19. Average review rating for each category.
select category,
round(avg(review_rating),2) as AverageReview
from customer
group by category
order by AverageReview desc;

-- 20. Which location has the highest number of customers?
select location ,
count(*) as TotalUsers
from customer
group by location
order by TotalUsers desc
limit 5;

-- 21. Compare revenue by shipping type.
select shipping_type, 
sum(purchase_amount) as TotalRevenue
from customer
group by shipping_type
order by TotalRevenue desc;

-- 22. Find products with an average rating greater than 3.
select item_purchased,
round(avg(review_rating),2) as AverageRating
from customer
group by item_purchased
having avg(review_rating) >= 3;


-- Compare the average spending of male and female customers above 30 years of age whose average purchase amount exceeds 50.
select gender,
avg(purchase_amount) as AverageSpend
from customer
where age>30
group by gender
having avg(purchase_amount) > 50
order by AverageSpend desc;

-- CORRELATED SUBQUERY
-- Find customers whose purchase amount is greater than the average purchase amount of their own age group.
select customer_id,
		age_group,
        purchase_amount
FROM customer c1
WHERE purchase_amount >
      (
          SELECT AVG(purchase_amount)
          FROM customer c2
          WHERE c1.age_group = c2.age_group
      )
      order by purchase_amount desc
      limit 5;





